### ISSUE TITLE
Potential ch8 and ch9 edge case bug

### ISSUE THREAD

**Issue by freq-mod** [nukeykt/Nuked-OPLL#13]
It's either: actual YM2413 bug, Furnace bug or Nuked-OPLL bug. 
[OPLL.zip](https://github.com/nukeykt/Nuked-OPLL/files/10306929/OPLL.zip) - contains .fur file and Furance .wav output using Nuked-OPLL core. There is a slight whine after note off on OPLL channels 8 and 9. ~~This is probably caused by setting egt on op1 causing it to sustain in ch 8 and 9 only.~~ Problem is, is this intentional, as register view is apparently fine....

Actual hw recording would be needed, but I dont have access to one... It doesnt occur on MAME and emu2413 cores.

**Comment by nukeykt** [comment]
maybe some issue in rhythm mode logic, it uses these channels
