### ISSUE TITLE
Question on formula in application of block in the phase increment calculation

### ISSUE THREAD

**Issue by Eugeny1** [nukeykt/Nuked-OPLL#4]
This is rather a question than issue.

How did you come to the following code:

    freq = chip->c_fnum << 1;
    ...
    freq += freq >> 7;
    ....
    /* Apply block */
    freq = (freq << block) >> 1;
    chip->pg_inc = (freq * pg_multi[chip->c_multi]) >> 1;

this code will take one 17-bit mux for barrel shifter and at least 15x5 multiplier, while the following code

    chip->pg_inc = (((chip->c_fnum << 1) + vibrato) * pg_multi[chip->c_multi]) << block) >> 2;

will require 11x5 multiplier and 19-bit-wide mux. 4 extra bits for multiplication must have more cost in silicon than a mux (unless multiplication is pipelined, and I doubt that given the timing constraints).

The footprint would not be a problem, if your code would not lose two LSbs when block is 0.
And again, this would not be a problem if freq is always even, but you add vibrato after shifting the freq left one bit, and the resulting value may become odd.

Example:
- F-number of 'b1_1100_0000;
- multi is 'b1100
- vibrato enabled.

    freq = chip->c_fnum << 1;

leads to freq='b11_1000_0000

    case 2:
        freq += freq >> 7;

leads to freq='b11_1000_0111

    freq = (freq << block) >> 1;

leads to freq='b1_1100_0011

    chip->pg_inc = (freq * pg_multi[chip->c_multi]) >> 1;

leads to 'ha92 ('b1010_1001_0010) with lowest bits having their weight lost (with another code at the beginning of the post returning 'ha95).

**Comment by nukeykt** [comment]
Hope this picture will explain how it works on silicon.
![rect2773](https://user-images.githubusercontent.com/15833655/91463273-2a5b0c00-e8c6-11ea-85da-529b27862255.jpg)
Also this code should explain how MULTI is working using one adder
: https://pastebin.com/KTTZmctS
